name: CI setup

runs:
  using: "composite"

  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "yarn"
        cache-dependency-path: |
          yarn.lock
          patches/*.patch

    - name: Install Dependencies
      run: yarn install --frozen-lockfile
      shell: bash
