name: CI setup

runs:
  using: "composite"

  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "pnpm"

    - run: corepack enable

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile --ignore-scripts
