name: Add status to commit
description: Add status to commit

runs:
  using: "composite"
  steps:
    - name: Add URL to vercel deployment through *.prs.webstudio.is
      uses: actions/github-script@v6
      with:
        script: |
          const branch = context.payload.pull_request?.head?.ref ?? context.payload.ref?.replace('refs/heads/', '')
          const sha = context.payload.pull_request?.head?.sha ?? context.sha;

          const status = {
            state: 'success',
            target_url: `https://${branch.toLowerCase().replace(/[^a-z0-9-]+/g, '')}.prs.webstudio.is`,
            description: 'click details to see the deployment',
            context: '⭐ EEE Apps Webstudio URL'
          };

          github.rest.repos.createCommitStatus({
            ...context.repo,
            sha,
            ...status
          });
