name: Add status to commit

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  statuses: write # to fetch code (actions/checkout)

jobs:
  checks:
    timeout-minutes: 20

    env:
      DATABASE_URL: postgres://
      AUTH_SECRET: test

    runs-on: ubuntu-latest

    steps:
      - name: Add URL to vercel deployment through *.prs.webstudio.is
        uses: actions/github-script@v6
        with:
          script: |

            const branch = context.payload.ref ?? context.payload.pull_request.head.ref;
            console.log('branch', branch);
            console.log('context.repo', JSON.stringify(context.repo));

            const sha = context.payload.pull_request?.head?.sha ?? context.sha;

            const status = {
              state: 'success',
              target_url: 'http://example.com',
              description: 'Description of the status',
              context: '🟠 Context of the status'
            };

            console.log(JSON.stringify(
              {...context.repo,
                sha,
              ...status
              }));

            github.rest.repos.createCommitStatus({
              ...context.repo,
              sha,
              ...status
            });
