name: Chromatic

on: [push]

jobs:
  chromatic:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          [designer-app, css-engine, design-system, icons, image, react-sdk]
        include:
          - project: designer-app
            chromaticToken: ${{ secrets.CHROMATIC_DESIGNER_APP_TOKEN }}
            workingDir: apps/designer

          - project: css-engine
            chromaticToken: ${{ secrets.CHROMATIC_CSS_ENGINE_TOKEN }}
            workingDir: packages/css-engine

          - project: design-system
            chromaticToken: ${{ secrets.CHROMATIC_DESIGN_SYSTEM_TOKEN }}
            workingDir: packages/design-system

          - project: icons
            chromaticToken: ${{ secrets.CHROMATIC_ICONS_TOKEN }}
            workingDir: packages/icons

          - project: image
            chromaticToken: ${{ secrets.CHROMATIC_IMAGE_TOKEN }}
            workingDir: packages/image

          - project: react-sdk
            chromaticToken: ${{ secrets.CHROMATIC_REACT_SDK_TOKEN }}
            workingDir: packages/react-sdk

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup

      - name: Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ matrix.chromaticToken }}
          workingDir: ${{ matrix.workingDir }}
