name: Main workflow

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  checks:
    timeout-minutes: 20

    env:
      DATABASE_URL: postgres://
      AUTH_SECRET: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # HEAD commit instead of merge commit

      - uses: ./.github/actions/ci-setup

      - uses: actions/cache@v3
        with:
          path: |
            ./node_modules/.cache/prettier/.prettier-cache
          key: checks-${{ github.sha }}
          restore-keys: checks-

      - run: pnpm prettier --cache --check "**/*.{js,md,ts,tsx}"

      - run: pnpm turbo run size-test build checks dts
