name: Main workflow

on: [push]

jobs:
  checks:
    timeout-minutes: 20

    env:
      NODE_ENV: test
      DATABASE_URL: postgres://
      AUTH_SECRET: test
      TURBO_REMOTE_ONLY: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup

      - run: pnpm build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      - run: pnpm checks
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
