name: Main workflow

on: [push]

env:
  TURBO_REMOTE_ONLY: true
  TURBO_TEAM: <FILL_THIS_IN>
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  checks:
    timeout-minutes: 20

    env:
      DATABASE_URL: postgres://
      AUTH_SECRET: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup

      - run: pnpm turbo run size-test build checks
