name: Migrate

on:
  push:
    branches:
      - "migrate"

jobs:
  migrate:
    runs-on: ubuntu-latest

    environment:
      name: "postgres_development"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }} # HEAD commit instead of merge commit

      - uses: ./.github/actions/migrate
        id: migrate
        name: Migrate
        with:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
