name: Publish packages on NPM 📦
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DATABASE_URL: postgres://
      AUTH_SECRET: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn
      - run: yarn turbo run build
      - run: yarn turbo run publish-to-npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
