name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/github-script@v7
      id: my-script
      with:
        result-encoding: string
        retries: 3
        script: |
          const latestRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const latestTag = await github.rest.git.getRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `tags/${latestRelease.data.tag_name}`,
          });
          console.log(latestTag.data.object.sha)
          const commits = await github.rest.repos.compareCommitsWithBasehead({
            owner: context.repo.owner,
            repo: context.repo.repo,
            basehead: `refs/tags/0.169...refs/tags/0.170.0`,
          });
          commits.data.commits.forEach(commit => {
            console.log(commit.sha)
            console.log(commit.commit.message)
            console.log(commit.html_url)
            console.log(commit.author.login)
            console.log('====')
          })
