name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: ardalanamini/auto-changelog@v4
      id: changelog
      with:
        commit-types: |
          feat: Features
          fix: Fixes
          docs: Documentation
          experimental: Experimental
