name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/github-script@v7
      id: my-script
      with:
        result-encoding: string
        retries: 3
        script: |
          const latestRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const latestTag = await github.rest.git.getRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_sha: `tags/${latestRelease?.data?.tag_name}`,
          });
          console.log(latestTag)
