name: Vercel Deploy

on:
  push:
    branches:
      - "*.staging"

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: vercel-deploy-${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  statuses: write # This is required for the GitHub Script createCommitStatus to work

jobs:
  deployment:
    strategy:
      matrix:
        environment: [staging]

    environment:
      name: ${{ matrix.environment }}

    timeout-minutes: 20

    runs-on: ubuntu-latest

    env:
      environment: staging

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }} # HEAD commit instead of merge commit

      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: pnpm

      - uses: ./.github/actions/vercel
        id: vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          ref-name: ${{ github.ref_name }}
          sha: ${{ github.sha }}
          environment: ${{ matrix.environment }}

      - name: Show
        run: |
          echo "domain=${{ steps.vercel.outputs.domain }}"
          echo "inspect-url=${{ steps.vercel.outputs.inspect-url }}"
          echo "alias=${{ steps.vercel.outputs.alias }}"

      - uses: ./.github/actions/add-status
        with:
          title: "⏰ Vercel Inspection"
          description: "Vercel logs"
          url: "${{ steps.vercel.outputs.inspect-url }}"

      - uses: ./.github/actions/add-status
        with:
          title: "⭐ Apps Webstudio URL"
          description: "Vercel logs"
          url: "https://${{ steps.vercel.outputs.alias }}.${{ matrix.environment }}.vercel.app"
