name: Vercel Deploy

on:
  push:
    branches:
      - "*.staging"

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: vercel-deploy-${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  deployment:
    environment:
      name: staging

    timeout-minutes: 20

    runs-on: ubuntu-latest

    env:
      SHORT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }} # HEAD commit instead of merge commit

      - id: branch
        run: |
          CLEANED_BRANCH_NAME=$( echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9_-]//g' | tr A-Z a-z | tr _ - | sed 's/-\{2,\}/-/g' )
          echo "::set-output name=value::${CLEANED_BRANCH_NAME}"

      - id: short_sha
        run: |
          SHORT_SHA=$( echo "value=$(echo ${{ github.sha }} | cut -c1-7)" )
          echo "::set-output name=value::${SHORT_SHA}"

      - name: Echo Branch Name After CLeanup
        run: echo "Hello, world! ${{  steps.branch.outputs.value }} SHA ${{ steps.short_sha.outputs.value }}"
