name: Vercel Deploy

on:
  push:
    branches:
      - "*.staging"

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: vercel-deploy-${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  statuses: write # This is required for the GitHub Script createCommitStatus to work

jobs:
  deployment:
    environment:
      name: staging

    timeout-minutes: 20

    runs-on: ubuntu-latest

    env:
      SHORT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }} # HEAD commit instead of merge commit

      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: pnpm

      - uses: ./.github/actions/vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          ref-name: ${{ github.ref_name }}
          sha: ${{ github.sha }}
